# Site settings
title: takashi
email: tak1240@gmail.com
description: my site.
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: tak0303
github_username:  takashi

# Build settings
markdown: kramdown
