# Site settings
title: takashi
email: tak1240@gmail.com
description: my site.
avatar: http://ja.gravatar.com/userimage/35729278/49f65a5e147ef8802eba86172fa0e1eb.jpg?size=200
twitter_username: tak0303
github_username:  takashi

# Build settings
markdown: kramdown
